"""Build a flood scenario on demand: from a height and a reach, or from a hand-picked set of cut roads.

The 60 preset floods (datasets/synthetic/flood_scenarios.csv) were generated by one rule, and this module applies the same rule to any
parameters, so a judge can ask for "a 3 m flood reaching 800 m from the rivers" and get a scenario consistent with the presets:

    a road segment is cut        if its midpoint is lower than `height_m` above the nearest river point AND within `distance_m` of it;
    a facility is flooded        by the same test, and is then out of service with probability `outage_prob`.

The rule is a simplification of flood physics, not a hydraulic model (see datasets/synthetic/ASSUMPTIONS.md). The per-segment and
per-facility distances and heights come from REAL rivers (OpenStreetMap) and terrain (AWS tiles), written by
datasets/build_flood_features.py.
"""
from pathlib import Path

import numpy as np
import pandas as pd

from .scenarios import Scenario

DATA = Path(__file__).resolve().parent.parent / "datasets"
OUTAGE_PROB = 0.5   # same assumption as the preset floods


class FloodFeatures:
    """Distance to the nearest river and height above it for every road segment and facility."""

    def __init__(self, data_dir=DATA):
        f = pd.read_csv(Path(data_dir) / "synthetic" / "flood_features.csv")
        seg, fac = f[f.kind == "road_segment"], f[f.kind == "facility"]
        self.seg_id = seg.id.to_numpy(int)
        self.seg_d, self.seg_h = seg.dist_river_m.to_numpy(float), seg.height_above_river_m.to_numpy(float)
        self.fac_id = fac.id.to_numpy(int)
        self.fac_d, self.fac_h = fac.dist_river_m.to_numpy(float), fac.height_above_river_m.to_numpy(float)

    def parametric(self, height_m: float, distance_m: float, seed: int = 42, outage_prob: float = OUTAGE_PROB, name: str = "custom") -> Scenario:
        cut = (self.seg_h < height_m) & (self.seg_d < distance_m)
        flooded = (self.fac_h < height_m) & (self.fac_d < distance_m)
        out = flooded & (np.random.default_rng(seed).random(len(self.fac_id)) < outage_prob)
        return Scenario(name=name, severity="custom", cut_segments=frozenset(int(i) for i in self.seg_id[cut]),
                        out_facilities=frozenset(int(i) for i in self.fac_id[out]))


def manual(cut_segments, out_facilities=(), name: str = "custom") -> Scenario:
    return Scenario(name=name, severity="custom", cut_segments=frozenset(int(i) for i in cut_segments),
                    out_facilities=frozenset(int(i) for i in out_facilities))
